#:import FadeTransition kivy.uix.screenmanager.FadeTransition

ScreenManager:
    id: screen_manager
    transition: FadeTransition(duration=0.2) # duration controla qué tan rápido es (en segundos)

    # =========================================================
    # 1. PANTALLA: CARRITO / COMPRAS RÁPIDAS (cart)
    # =========================================================
    MDScreen:
        name: "cart"
        md_bg_color: self.theme_cls.backgroundColor

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "15dp"

            MDLabel:
                text: "Carrito de Compras"
                font_style: "Headline"
                role: "medium"
                halign: "center"
                size_hint_y: None
                height: "50dp"

            MDCard:
                size_hint_y: 1
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDScrollView:
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "20dp"
                        
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "circle-outline"
                            MDLabel:
                                text: "2L de Leche Entera"
                                bold: True
                            MDLabel:
                                text: "$2.500"
                                halign: "right"
                                theme_text_color: "Hint"
                        
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "circle-outline"
                            MDLabel:
                                text: "1kg de Arroz"
                                bold: True
                            MDLabel:
                                text: "$1.200"
                                halign: "right"
                                theme_text_color: "Hint"
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "circle-outline"
                            MDLabel:
                                text: "Huevos (Docena)"
                                bold: True
                            MDLabel:
                                text: "$3.000"
                                halign: "right"
                                theme_text_color: "Hint"

            MDCard:
                size_hint: None, None
                size: "275dp", "60dp"
                pos_hint: {"center_x": 0.5}
                radius: [30,]
                elevation: 2
                padding: "8dp"

                MDBoxLayout:
                    orientation: "horizontal"
                    spacing: "15dp"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "cart"
                        style: "tonal"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cart")

                    MDIconButton:
                        icon: "cupboard"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cupboard")

                    MDIconButton:
                        icon: "home"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("home")

                    MDIconButton:
                        icon: "clipboard-list"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("clipboard-list")

                    MDIconButton:
                        icon: "cog"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cog")

    # =========================================================
    # 2. PANTALLA: DESPENSA / INVENTARIO (cupboard)
    # =========================================================
    MDScreen:
        name: "cupboard"
        md_bg_color: self.theme_cls.backgroundColor

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "15dp"

            MDLabel:
                text: "Inventario de Despensa"
                font_style: "Headline"
                role: "medium"
                halign: "center"
                size_hint_y: None
                height: "50dp"

            MDCard:
                size_hint_y: 1
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDScrollView:
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "20dp"
                        
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "food-apple"
                                theme_text_color: "Custom"
                                text_color: "green"
                            MDLabel:
                                text: "Frijoles (500g)"
                                bold: True
                            MDLabel:
                                text: "Suficiente"
                                halign: "right"
                                theme_text_color: "Custom"
                                text_color: "green"
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "bottle-wine"
                                theme_text_color: "Custom"
                                text_color: "orange"
                            MDLabel:
                                text: "Aceite de Oliva"
                                bold: True
                            MDLabel:
                                text: "1 Botella"
                                halign: "right"
                                theme_text_color: "Custom"
                                text_color: "orange"
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "shaker"
                                theme_text_color: "Custom"
                                text_color: "red"
                            MDLabel:
                                text: "Sal Común"
                                bold: True
                            MDLabel:
                                text: "Por agotarse"
                                halign: "right"
                                theme_text_color: "Custom"
                                text_color: "red"

            MDCard:
                size_hint: None, None
                size: "275dp", "60dp"
                pos_hint: {"center_x": 0.5}
                radius: [30,]
                elevation: 2
                padding: "8dp"

                MDBoxLayout:
                    orientation: "horizontal"
                    spacing: "15dp"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "cart"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cart")

                    MDIconButton:
                        icon: "cupboard"
                        style: "tonal"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cupboard")

                    MDIconButton:
                        icon: "home"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("home")

                    MDIconButton:
                        icon: "clipboard-list"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("clipboard-list")

                    MDIconButton:
                        icon: "cog"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cog")

    # =========================================================
    # 3. PANTALLA: INICIO (home - Tu diseño original)
    # =========================================================
    MDScreen:
        name: "home"
        md_bg_color: self.theme_cls.backgroundColor

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "15dp"
            
            Image:
                source: "despensapp_logo_example.jpg"
                size_hint: None, None
                size: "230dp", "100dp"
                allow_stretch: True
                keep_ratio: True
                pos_hint: {"center_x": 0.5}

            MDCard:
                size_hint_y: None
                height: "100dp"
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDBoxLayout:
                    spacing: "15dp"
                    MDIcon:
                        icon: "currency-usd"
                        font_size: "48sp"
                        pos_hint: {"center_y": .5}
                        theme_text_color: "Custom"
                        text_color: "green"
                    MDBoxLayout:
                        orientation: "vertical"
                        pos_hint: {"center_y": .5}
                        MDLabel:
                            text: "Gasto Semanal"
                            theme_text_color: "Hint"
                        MDLabel:
                            text: "$ 45.000"
                            font_style: "Headline"
                            role: "small"
                            bold: True

            MDCard:
                size_hint_y: None
                height: "100dp"
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDBoxLayout:
                    spacing: "15dp"
                    MDIcon:
                        icon: "alert-circle-outline"
                        font_size: "48sp"
                        pos_hint: {"center_y": .5}
                        theme_text_color: "Custom"
                        text_color: "red"
                    MDBoxLayout:
                        orientation: "vertical"
                        pos_hint: {"center_y": .5}
                        MDLabel:
                            text: "Por Caducar"
                            theme_text_color: "Hint"
                        MDLabel:
                            text: "Leche (Mañana)"
                            font_style: "Title"
                            role: "medium"
                            bold: True

            MDCard:
                size_hint_y: None
                height: "100dp"
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDBoxLayout:
                    spacing: "15dp"
                    MDIcon:
                        icon: "chef-hat"
                        font_size: "48sp"
                        pos_hint: {"center_y": .5}
                        theme_text_color: "Custom"
                        text_color: "orange"
                    MDBoxLayout:
                        orientation: "vertical"
                        pos_hint: {"center_y": .5}
                        MDLabel:
                            text: "Receta Sugerida"
                            theme_text_color: "Hint"
                        MDLabel:
                            text: "Arroz con Huevo"
                            font_style: "Title"
                            role: "medium"
                            bold: True

            MDCard:
                size_hint: None, None
                size: "275dp", "60dp"
                pos_hint: {"center_x": 0.5}
                radius: [30,]
                elevation: 2
                padding: "8dp"

                MDBoxLayout:
                    orientation: "horizontal"
                    spacing: "15dp"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "cart"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cart")

                    MDIconButton:
                        icon: "cupboard"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cupboard")

                    MDIconButton:
                        icon: "home"
                        style: "tonal"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("home")

                    MDIconButton:
                        icon: "clipboard-list"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("clipboard-list")

                    MDIconButton:
                        icon: "cog"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cog")

    # =========================================================
    # 4. PANTALLA: LISTA DE SUPERMERCADO (clipboard-list)
    # =========================================================
    MDScreen:
        name: "clipboard-list"
        md_bg_color: self.theme_cls.backgroundColor

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "15dp"

            MDLabel:
                text: "Lista del Supermercado"
                font_style: "Headline"
                role: "medium"
                halign: "center"
                size_hint_y: None
                height: "50dp"

            MDCard:
                size_hint_y: 1
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDScrollView:
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "20dp"
                        
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "format-list-bulleted"
                                theme_text_color: "Custom"
                                text_color: "blue"
                            MDBoxLayout:
                                orientation: "vertical"
                                MDLabel:
                                    text: "Compra Quincenal"
                                    bold: True
                                MDLabel:
                                    text: "15 Artículos"
                                    theme_text_color: "Hint"
                            MDIcon:
                                icon: "chevron-right"
                                theme_text_color: "Hint"
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "cake-variant"
                                theme_text_color: "Custom"
                                text_color: "pink"
                            MDBoxLayout:
                                orientation: "vertical"
                                MDLabel:
                                    text: "Cena de Cumpleaños"
                                    bold: True
                                MDLabel:
                                    text: "8 Artículos"
                                    theme_text_color: "Hint"
                            MDIcon:
                                icon: "chevron-right"
                                theme_text_color: "Hint"

            MDCard:
                size_hint: None, None
                size: "275dp", "60dp"
                pos_hint: {"center_x": 0.5}
                radius: [30,]
                elevation: 2
                padding: "8dp"

                MDBoxLayout:
                    orientation: "horizontal"
                    spacing: "15dp"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "cart"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cart")

                    MDIconButton:
                        icon: "cupboard"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cupboard")

                    MDIconButton:
                        icon: "home"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("home")

                    MDIconButton:
                        icon: "clipboard-list"
                        style: "tonal"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("clipboard-list")

                    MDIconButton:
                        icon: "cog"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cog")

    # =========================================================
    # 5. PANTALLA: CONFIGURACIÓN (cog)
    # =========================================================
    MDScreen:
        name: "cog"
        md_bg_color: self.theme_cls.backgroundColor

        MDBoxLayout:
            orientation: "vertical"
            padding: "20dp"
            spacing: "15dp"

            MDLabel:
                text: "Configuración"
                font_style: "Headline"
                role: "medium"
                halign: "center"
                size_hint_y: None
                height: "50dp"

            MDCard:
                size_hint_y: 1
                radius: [20,]
                elevation: 1
                padding: "20dp"
                MDScrollView:
                    MDBoxLayout:
                        orientation: "vertical"
                        adaptive_height: True
                        spacing: "30dp"
                        
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "account"
                            MDLabel:
                                text: "Perfil de Usuario"
                                bold: True
                            MDIcon:
                                icon: "chevron-right"
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "bell-outline"
                            MDLabel:
                                text: "Notificaciones"
                                bold: True
                            MDSwitch:
                                active: True
                                pos_hint: {"center_y": .5}
                                
                        MDBoxLayout:
                            adaptive_height: True
                            spacing: "15dp"
                            MDIcon:
                                icon: "theme-light-dark"
                            MDLabel:
                                text: "Tema Oscuro"
                                bold: True
                            MDSwitch:
                                id: switch_tema
                                active: False
                                pos_hint: {"center_y": .5}
                                on_active: app.cambiar_tema(self.active)

            MDCard:
                size_hint: None, None
                size: "275dp", "60dp"
                pos_hint: {"center_x": 0.5}
                radius: [30,]
                elevation: 2
                padding: "8dp"

                MDBoxLayout:
                    orientation: "horizontal"
                    spacing: "15dp"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}

                    MDIconButton:
                        icon: "cart"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cart")

                    MDIconButton:
                        icon: "cupboard"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cupboard")

                    MDIconButton:
                        icon: "home"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("home")

                    MDIconButton:
                        icon: "clipboard-list"
                        style: "standard"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("clipboard-list")

                    MDIconButton:
                        icon: "cog"
                        style: "tonal"
                        pos_hint: {"center_y": 0.5}
                        on_release: app.cambiar_pantalla("cog")